'use strict';

FlashCards.words =
[
  { id: 1, level: 1, de: 'Hallo', en: 'Hello' },
  { id: 2, level: 1, de: 'Gutten Morgen', en: 'Good morning' },
  { id: 3, level: 1, de: 'Gutten Tag', en: 'Good day' },
  { id: 4, level: 1, de: 'Gutten Abend', en: 'Good evening' },
  { id: 5, level: 1, de: 'Gutte Nacht', en: 'Good night' },
  { id: 6, level: 1, de: 'Willkommen', en: 'Welcome' },
  { id: 7, level: 1, de: 'Auf Widersehen', en: 'Good bye' },
  { id: 8, level: 2, de: 'haben', en: 'to have' },
  { id: 9, level: 2, de: 'sein', en: 'to be' },
  { id: 10, level: 2, de: 'spielen', en: 'to play' },
  { id: 11, level: 2, de: 'machen', en: 'to do or make' },
  { id: 12, level: 2, de: 'tun', en: 'to do or make' },
  { id: 13, level: 2, de: 'schreiben', en: 'to write' },
  { id: 14, level: 2, de: 'treffen', en: 'to meet' },
  { id: 15, level: 2, de: 'fahren', en: 'to drive' },
  { id: 16, level: 2, de: 'schwimmen', en: 'to swim' },
  { id: 17, level: 2, de: 'laufen', en: 'to run' },
  { id: 18, level: 2, de: 'lesen', en: 'to read' },
  { id: 19, level: 2, de: 'sehen', en: 'to see' },
  { id: 20, level: 2, de: 'zeichnen', en: 'to draw' },
  { id: 21, level: 2, de: 'sammeln', en: 'to collect' },
  { id: 22, level: 2, de: 'ausgehen', en: 'to go out' },
  { id: 23, level: 2, de: 'fernsehen', en: 'to watch TV' },
  { id: 24, level: 2, de: 'gehen', en: 'to go' },
  { id: 25, level: 2, de: 'hören', en: 'to hear' },
  { id: 26, level: 2, de: 'essen', en: 'to eat' },
  { id: 27, level: 2, de: 'trinken', en: 'to drink' },
  { id: 28, level: 2, de: 'kochen', en: 'to cook' },
  { id: 29, level: 2, de: 'malen', en: 'to paint' },
  { id: 30, level: 2, de: 'schliessen', en: 'to close' },
  { id: 31, level: 2, de: 'bleiben', en: 'to stay' },
  { id: 32, level: 2, de: 'tanzen', en: 'to dance' },
  { id: 33, level: 2, de: 'spazieren', en: 'to walk' },
  { id: 34, level: 2, de: 'bringen', en: 'to bring' },
  { id: 35, level: 2, de: 'einkaufen', en: 'to shop' },
  { id: 36, level: 2, de: 'kaufen', en: 'to buy' },
  { id: 37, level: 2, de: 'wohnen', en: 'to live' },
  { id: 38, level: 2, de: 'geben', en: 'to give' },
  { id: 39, level: 2, de: 'nehmen', en: 'to take' },
  { id: 40, level: 2, de: 'sprechen', en: 'to speak' },
  { id: 41, level: 2, de: 'vergessen', en: 'to forget' },
  { id: 42, level: 2, de: 'kommen', en: 'to come' },
  { id: 43, level: 2, de: 'öffnen', en: 'to open' },
  { id: 44, level: 2, de: 'fragen', en: 'to ask' },
  { id: 45, level: 2, de: 'sagen', en: 'to say' },
  { id: 46, level: 2, de: 'suchen', en: 'to search' },
  { id: 47, level: 2, de: 'finden', en: 'to find' },
  { id: 48, level: 2, de: 'schlafen', en: 'to sleep' },
  { id: 49, level: 2, de: 'aufstehen', en: 'to stand up' },
  { id: 50, level: 2, de: 'frühstücken', en: 'to breakfast' },
  { id: 51, level: 2, de: 'bestellen', en: 'to order' },
  { id: 52, level: 2, de: 'einladen', en: 'to invite' },
  { id: 53, level: 2, de: 'lieben', en: 'to love' },
  { id: 54, level: 2, de: 'arbeiten', en: 'to work' },
  { id: 55, level: 2, de: 'mitkommen', en: 'to come with' },
  { id: 56, level: 2, de: 'anmachen', en: 'to turn on' },
  { id: 57, level: 2, de: 'ausmachen', en: 'to turn off' },
  { id: 58, level: 2, de: 'aufmachen', en: 'to open' },
  { id: 59, level: 2, de: 'zumachen', en: 'to close' },
  { id: 60, level: 2, de: 'bekommen', en: 'to get or receive' },
  { id: 61, level: 2, de: 'denken', en: 'to think' },
  { id: 62, level: 2, de: 'erklären', en: 'to explain' },
  { id: 63, level: 2, de: 'erzählen', en: 'to tell' },
  { id: 64, level: 2, de: 'besuchen', en: 'to visit' },
  { id: 65, level: 2, de: 'möchten', en: 'would like' },
  { id: 66, level: 2, de: 'mögen', en: 'to like' },
  { id: 67, level: 2, de: 'sollen', en: 'should, shall' },
  { id: 68, level: 2, de: 'wollen', en: 'to want' },
  { id: 69, level: 2, de: 'dürfen', en: 'may, to be allowed to' },
  { id: 70, level: 2, de: 'können', en: 'can, to be able to' },
  { id: 71, level: 2, de: 'müssen', en: 'must, to have to' }
];